def test_typeerror_2(self):
    with self.assertRaises(TypeError):
        is_prime(5)